#!/usr/bin/env python3
"""
yt_manifest.py — The per-show manifest, split into a human file and a machine file

One show's manifest used to be a single 20-column TSV. Five of those columns
are ever touched by a person; the other fifteen belong to the tools. In
practice the wide file was hard to hand-edit: the main correction target
(Song) sat ten columns right of the clip name, and the machine columns
rendered as walls of tabs (issue #251 review note).

The manifest is now two files joined on Clip:

  <date>-<artist-slug>.tsv           the LEAN EDIT FILE. Human columns first,
                                     then the read-only decision aids a person
                                     needs visible while picking a Song.

  <date>-<artist-slug>.machine.json  the MACHINE SIDECAR. Everything the tools
                                     own end to end, including Video ID and
                                     Upload Status — so the "blank Video ID is
                                     the work queue" invariant lives here.

  <date>-<artist-slug>.scan.json     unchanged: how the scan was run.

WHO WRITES WHAT

  A person edits ONLY the lean file, and only its human columns. The tools
  rewrite both files, but never overwrite a Song or Decision a person has
  typed (--reseed is the deliberate exception, and even it keeps Song).
  The read-only aid columns (Candidates, Lyric Hint) are regenerated by
  --identify on every run; edits to them do not survive and do not matter.

LEGACY MANIFESTS

  A pre-split 20-column manifest is recognized on load and migrated in place:
  machine columns move to the sidecar, the TSV is rewritten lean. The old
  file's values all survive — nothing is dropped in the split.
"""

import json
import os
from datetime import datetime, timezone

from yt_common import read_tsv, write_tsv


# ── schema ─────────────────────────────────────────────────────────────────

# The lean edit file. Human-owned columns first, in edit order; then the
# read-only aids --identify maintains. Keep this under ten columns — the
# whole point of the split is that a row fits in an eye-span.
HUMAN_FIELDS = ["Clip", "Decision", "Set Artist", "Song", "Cover", "Skip Reason"]
AID_FIELDS   = ["Candidates", "Lyric Hint"]
LEAN_FIELDS  = HUMAN_FIELDS + AID_FIELDS

# The machine sidecar, keyed by clip name. Every field the tools own.
MACHINE_FIELDS = [
    "Capture Order", "Capture Start", "Duration", "Size MB", "Integrity",
    "Set", "Confidence", "Evidence", "Setlist Pos",
    "Video ID", "Upload Status", "Title Set",
]

# The pre-split single-file schema, kept only so a legacy manifest can be
# recognized and migrated. Order matters: it is the old file's column order.
LEGACY_FIELDS = [
    "Clip", "Capture Order", "Capture Start", "Duration", "Size MB", "Integrity",
    "Set", "Set Artist",
    "Decision", "Skip Reason",
    "Song", "Confidence", "Evidence", "Candidates", "Lyric Hint",
    "Setlist Pos", "Cover",
    "Video ID", "Upload Status", "Title Set",
]

ALL_FIELDS = LEAN_FIELDS + MACHINE_FIELDS


def machine_path(manifest_path: str) -> str:
    """The sidecar that travels with a lean manifest TSV."""
    return manifest_path[:-4] + ".machine.json"


def blank_row() -> dict:
    """An empty merged row with every known column present."""
    return {field: "" for field in ALL_FIELDS}


# ── loading ────────────────────────────────────────────────────────────────

def load(manifest_path: str) -> list[dict]:
    """Read a manifest as merged rows (lean + machine), migrating if legacy.

    Returns rows carrying every column in ALL_FIELDS, in the lean file's row
    order. Rows present only in the sidecar (a clip whose lean row was
    hand-deleted) are appended last rather than lost — they may hold the only
    record that a clip was uploaded.
    """
    rows = read_tsv(manifest_path)
    if not rows:
        return []

    if _is_legacy(rows):
        return _migrate_legacy(manifest_path, rows)

    machine = _read_machine(machine_path(manifest_path))

    merged = []
    seen = set()
    for lean_row in rows:
        clip = (lean_row.get("Clip") or "").strip()
        if not clip:
            continue
        seen.add(clip)
        row = blank_row()
        row.update({k: (lean_row.get(k) or "") for k in LEAN_FIELDS})
        row.update(machine.get(clip, {}))
        row["Clip"] = clip
        merged.append(row)

    for clip, fields in machine.items():
        if clip in seen:
            continue
        row = blank_row()
        row["Clip"] = clip
        row.update(fields)
        merged.append(row)

    return merged


def save(manifest_path: str, rows: list[dict]) -> None:
    """Write merged rows back as the lean TSV + machine sidecar pair."""
    lean = [{k: (row.get(k) or "") for k in LEAN_FIELDS} for row in rows]
    write_tsv(manifest_path, lean, LEAN_FIELDS)

    machine = {}
    for row in rows:
        clip = (row.get("Clip") or "").strip()
        if not clip:
            continue
        machine[clip] = {k: (row.get(k) or "") for k in MACHINE_FIELDS}

    payload = {
        "updated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "clips": machine,
    }
    with open(machine_path(manifest_path), "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
        f.write("\n")


def _read_machine(path: str) -> dict[str, dict]:
    """Sidecar contents keyed by clip, or {} when absent or unreadable."""
    try:
        with open(path, encoding="utf-8") as f:
            payload = json.load(f)
    except (OSError, ValueError):
        return {}
    clips = payload.get("clips", {})
    return {clip: {k: (fields.get(k) or "") for k in MACHINE_FIELDS}
            for clip, fields in clips.items() if isinstance(fields, dict)}


# ── legacy migration ───────────────────────────────────────────────────────

def _is_legacy(rows: list[dict]) -> bool:
    """A pre-split manifest is recognized by its machine columns in the TSV."""
    header = set(rows[0].keys())
    return "Video ID" in header or "Capture Order" in header


def _migrate_legacy(manifest_path: str, rows: list[dict]) -> list[dict]:
    """Split a wide manifest in place. Every value survives the split."""
    merged = []
    for old in rows:
        clip = (old.get("Clip") or "").strip()
        if not clip:
            continue
        row = blank_row()
        row.update({k: (old.get(k) or "") for k in ALL_FIELDS if k in old})
        merged.append(row)

    save(manifest_path, merged)
    print(f"  Migrated legacy manifest to lean TSV + machine sidecar:\n"
          f"    {manifest_path}\n"
          f"    {machine_path(manifest_path)}")
    return merged
